version: '2'
services:
  db:
    image: mysql:5
    environment:
      MYSQL_DATABASE: freeway-analystic
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 33061:3306
  web:
    build: .
    command: "php artisan serve --host=0.0.0.0 --port=4000"
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - db
# RUN php artisan migrate
# RUN php artisan freeway:import